version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app:cached
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      - db


  db:
    image: arangodb:3.11.3
    environment:
      ARANGO_ROOT_PASSWORD: openSesame
    volumes:
      - arangodb-data:/var/lib/arangodb3

volumes:
  arangodb-data:
